version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-racehorse_db}
      POSTGRES_USER: ${DB_USER:-racehorse_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-racehorse_pass}
    # no ports, just internal networking
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    # no ports
    volumes:
      - redis_data:/data
