version: '3.8'

services:
  # PostgreSQL database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-racehorse_db}
      POSTGRES_USER: ${DB_USER:-racehorse_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-racehorse_pass}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Redis service for caching and Celery broker
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

  # Django web application
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DEBUG=${DEBUG:-1}
      - DATABASE_URL=postgresql://${DB_USER:-racehorse_user}:${DB_PASSWORD:-racehorse_pass}@db:${DB_PORT:-5432}/${DB_NAME:-racehorse_db}
      - REDIS_URL=redis://redis:${REDIS_PORT:-6379}/${REDIS_DB:-0}
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000

  # Celery worker for background tasks
  celery:
    build: .
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DEBUG=${DEBUG:-1}
      - DATABASE_URL=postgresql://${DB_USER:-racehorse_user}:${DB_PASSWORD:-racehorse_pass}@db:${DB_PORT:-5432}/${DB_NAME:-racehorse_db}
      - REDIS_URL=redis://redis:${REDIS_PORT:-6379}/${REDIS_DB:-0}
    depends_on:
      - db
      - redis
    command: celery -A racehorse_drf worker --loglevel=info

volumes:
  postgres_data:
  redis_data:
  media_volume:
