# Generated by Django 5.1.1 on 2025-08-15 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='track_configuration',
            field=models.CharField(choices=[('L', 'Left Handed'), ('R', 'Right Handed'), ('S', 'Straight')], max_length=2),
        ),
        migrations.AlterField(
            model_name='race',
            name='track_surface',
            field=models.CharField(choices=[('D', 'Dirt'), ('T', 'Turf'), ('S', 'Synthetic'), ('O', 'Other')], max_length=2),
        ),
    ]
