# Generated by Django 5.1.1 on 2025-08-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_race_track_configuration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='track_condition',
            field=models.CharField(choices=[('fast', 'Fast'), ('frozen', 'Frozen'), ('good', 'Good'), ('heavy', 'Heavy'), ('muddy', 'Muddy'), ('sloppy', 'Sloppy'), ('slow', 'Slow'), ('wet_fast', 'Wet Fast'), ('firm', 'Firm'), ('hard', 'Hard'), ('soft', 'Soft'), ('yielding', 'Yielding'), ('standard', 'Standard'), ('harsh', 'Harsh')], max_length=15),
        ),
        migrations.AlterField(
            model_name='race',
            name='track_configuration',
            field=models.CharField(choices=[('left_handed', 'Left Handed'), ('right_handed', 'Right Handed'), ('straight', 'Straight')], max_length=15),
        ),
    ]
