name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: racehorse_db
          POSTGRES_USER: racehorse_user
          POSTGRES_PASSWORD: racehorse_pass
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U racehorse_user -d racehorse_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

      redis:
        image: redis:7-alpine
        ports: ["6379:6379"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Docker Compose
        run: pip install docker-compose

      - name: Build and start containers
        run: docker-compose up -d --build

      - name: Run Django tests
        run: docker-compose run --rm web python manage.py test
